//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.School
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Запись.
    /// </summary>
    // *** Start programmer edit section *** (Запись CustomAttributes)

    // *** End programmer edit section *** (Запись CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаписьE", new string[] {
            "времяначало as \'Времяначало\'",
            "Времяконца as \'Времяконца\'",
            "Услуги as \'Услуги\'",
            "Услуги.стоимость as \'Стоимость\'"}, Hidden=new string[] {
            "Услуги.стоимость"})]
    [AssociatedDetailViewAttribute("ЗаписьE", "клиенты", "клиентыE", true, "", "Клиенты", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЗаписьE", "Услуги", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "стоимость")]
    [View("ЗаписьL", new string[] {
            "времяначало as \'Времяначало\'",
            "Времяконца as \'Времяконца\'",
            "Услуги.стоимость as \'Стоимость\'"})]
    public class Запись : ICSSoft.STORMNET.DataObject
    {
        
        private int fвремяначало;
        
        private int fВремяконца;
        
        private IIS.School.Услуги fУслуги;
        
        private IIS.School.DetailArrayOfклиенты fклиенты;
        
        // *** Start programmer edit section *** (Запись CustomMembers)

        // *** End programmer edit section *** (Запись CustomMembers)

        
        /// <summary>
        /// Времяконца.
        /// </summary>
        // *** Start programmer edit section *** (Запись.Времяконца CustomAttributes)

        // *** End programmer edit section *** (Запись.Времяконца CustomAttributes)
        public virtual int Времяконца
        {
            get
            {
                // *** Start programmer edit section *** (Запись.Времяконца Get start)

                // *** End programmer edit section *** (Запись.Времяконца Get start)
                int result = this.fВремяконца;
                // *** Start programmer edit section *** (Запись.Времяконца Get end)

                // *** End programmer edit section *** (Запись.Времяконца Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.Времяконца Set start)

                // *** End programmer edit section *** (Запись.Времяконца Set start)
                this.fВремяконца = value;
                // *** Start programmer edit section *** (Запись.Времяконца Set end)

                // *** End programmer edit section *** (Запись.Времяконца Set end)
            }
        }
        
        /// <summary>
        /// времяначало.
        /// </summary>
        // *** Start programmer edit section *** (Запись.времяначало CustomAttributes)

        // *** End programmer edit section *** (Запись.времяначало CustomAttributes)
        public virtual int времяначало
        {
            get
            {
                // *** Start programmer edit section *** (Запись.времяначало Get start)

                // *** End programmer edit section *** (Запись.времяначало Get start)
                int result = this.fвремяначало;
                // *** Start programmer edit section *** (Запись.времяначало Get end)

                // *** End programmer edit section *** (Запись.времяначало Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.времяначало Set start)

                // *** End programmer edit section *** (Запись.времяначало Set start)
                this.fвремяначало = value;
                // *** Start programmer edit section *** (Запись.времяначало Set end)

                // *** End programmer edit section *** (Запись.времяначало Set end)
            }
        }
        
        /// <summary>
        /// Запись.
        /// </summary>
        // *** Start programmer edit section *** (Запись.Услуги CustomAttributes)

        // *** End programmer edit section *** (Запись.Услуги CustomAttributes)
        [PropertyStorage(new string[] {
                "Услуги"})]
        [NotNull()]
        public virtual IIS.School.Услуги Услуги
        {
            get
            {
                // *** Start programmer edit section *** (Запись.Услуги Get start)

                // *** End programmer edit section *** (Запись.Услуги Get start)
                IIS.School.Услуги result = this.fУслуги;
                // *** Start programmer edit section *** (Запись.Услуги Get end)

                // *** End programmer edit section *** (Запись.Услуги Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.Услуги Set start)

                // *** End programmer edit section *** (Запись.Услуги Set start)
                this.fУслуги = value;
                // *** Start programmer edit section *** (Запись.Услуги Set end)

                // *** End programmer edit section *** (Запись.Услуги Set end)
            }
        }
        
        /// <summary>
        /// Запись.
        /// </summary>
        // *** Start programmer edit section *** (Запись.клиенты CustomAttributes)

        // *** End programmer edit section *** (Запись.клиенты CustomAttributes)
        public virtual IIS.School.DetailArrayOfклиенты клиенты
        {
            get
            {
                // *** Start programmer edit section *** (Запись.клиенты Get start)

                // *** End programmer edit section *** (Запись.клиенты Get start)
                if ((this.fклиенты == null))
                {
                    this.fклиенты = new IIS.School.DetailArrayOfклиенты(this);
                }
                IIS.School.DetailArrayOfклиенты result = this.fклиенты;
                // *** Start programmer edit section *** (Запись.клиенты Get end)

                // *** End programmer edit section *** (Запись.клиенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.клиенты Set start)

                // *** End programmer edit section *** (Запись.клиенты Set start)
                this.fклиенты = value;
                // *** Start programmer edit section *** (Запись.клиенты Set end)

                // *** End programmer edit section *** (Запись.клиенты Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаписьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьE", typeof(IIS.School.Запись));
                }
            }
            
            /// <summary>
            /// "ЗаписьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьL", typeof(IIS.School.Запись));
                }
            }
        }
    }
}
