//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.School
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Интерфейс.
    /// </summary>
    // *** Start programmer edit section *** (Интерфейс CustomAttributes)

    // *** End programmer edit section *** (Интерфейс CustomAttributes)
    public interface Интерфейс
    {
        
        // *** Start programmer edit section *** (Интерфейс CustomMembers)

        // *** End programmer edit section *** (Интерфейс CustomMembers)

    }
}
