//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.School
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиенты.
    /// </summary>
    // *** Start programmer edit section *** (клиенты CustomAttributes)

    // *** End programmer edit section *** (клиенты CustomAttributes)
    [AutoAltered()]
    [Caption("Клиенты")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("клиентыE", new string[] {
            "Имя as \'Имя\'",
            "Фамилия as \'Фамилия\'",
            "Отчетво as \'Отчетво\'",
            "Пол as \'Пол\'"})]
    public class клиенты : ICSSoft.STORMNET.DataObject
    {
        
        private string fИмя;
        
        private string fФамилия;
        
        private string fОтчетво;
        
        private IIS.School.ПОЛ fПол;
        
        private IIS.School.Запись fЗапись;
        
        // *** Start programmer edit section *** (клиенты CustomMembers)

        // *** End programmer edit section *** (клиенты CustomMembers)

        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (клиенты.Имя CustomAttributes)

        // *** End programmer edit section *** (клиенты.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (клиенты.Имя Get start)

                // *** End programmer edit section *** (клиенты.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (клиенты.Имя Get end)

                // *** End programmer edit section *** (клиенты.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (клиенты.Имя Set start)

                // *** End programmer edit section *** (клиенты.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (клиенты.Имя Set end)

                // *** End programmer edit section *** (клиенты.Имя Set end)
            }
        }
        
        /// <summary>
        /// Отчетво.
        /// </summary>
        // *** Start programmer edit section *** (клиенты.Отчетво CustomAttributes)

        // *** End programmer edit section *** (клиенты.Отчетво CustomAttributes)
        [StrLen(255)]
        public virtual string Отчетво
        {
            get
            {
                // *** Start programmer edit section *** (клиенты.Отчетво Get start)

                // *** End programmer edit section *** (клиенты.Отчетво Get start)
                string result = this.fОтчетво;
                // *** Start programmer edit section *** (клиенты.Отчетво Get end)

                // *** End programmer edit section *** (клиенты.Отчетво Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (клиенты.Отчетво Set start)

                // *** End programmer edit section *** (клиенты.Отчетво Set start)
                this.fОтчетво = value;
                // *** Start programmer edit section *** (клиенты.Отчетво Set end)

                // *** End programmer edit section *** (клиенты.Отчетво Set end)
            }
        }
        
        /// <summary>
        /// Пол.
        /// </summary>
        // *** Start programmer edit section *** (клиенты.Пол CustomAttributes)

        // *** End programmer edit section *** (клиенты.Пол CustomAttributes)
        public virtual IIS.School.ПОЛ Пол
        {
            get
            {
                // *** Start programmer edit section *** (клиенты.Пол Get start)

                // *** End programmer edit section *** (клиенты.Пол Get start)
                IIS.School.ПОЛ result = this.fПол;
                // *** Start programmer edit section *** (клиенты.Пол Get end)

                // *** End programmer edit section *** (клиенты.Пол Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (клиенты.Пол Set start)

                // *** End programmer edit section *** (клиенты.Пол Set start)
                this.fПол = value;
                // *** Start programmer edit section *** (клиенты.Пол Set end)

                // *** End programmer edit section *** (клиенты.Пол Set end)
            }
        }
        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (клиенты.Фамилия CustomAttributes)

        // *** End programmer edit section *** (клиенты.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (клиенты.Фамилия Get start)

                // *** End programmer edit section *** (клиенты.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (клиенты.Фамилия Get end)

                // *** End programmer edit section *** (клиенты.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (клиенты.Фамилия Set start)

                // *** End programmer edit section *** (клиенты.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (клиенты.Фамилия Set end)

                // *** End programmer edit section *** (клиенты.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.School.Запись.
        /// </summary>
        // *** Start programmer edit section *** (клиенты.Запись CustomAttributes)

        // *** End programmer edit section *** (клиенты.Запись CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Запись"})]
        public virtual IIS.School.Запись Запись
        {
            get
            {
                // *** Start programmer edit section *** (клиенты.Запись Get start)

                // *** End programmer edit section *** (клиенты.Запись Get start)
                IIS.School.Запись result = this.fЗапись;
                // *** Start programmer edit section *** (клиенты.Запись Get end)

                // *** End programmer edit section *** (клиенты.Запись Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (клиенты.Запись Set start)

                // *** End programmer edit section *** (клиенты.Запись Set start)
                this.fЗапись = value;
                // *** Start programmer edit section *** (клиенты.Запись Set end)

                // *** End programmer edit section *** (клиенты.Запись Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "клиентыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View клиентыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("клиентыE", typeof(IIS.School.клиенты));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of клиенты.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfклиенты CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfклиенты CustomAttributes)
    public class DetailArrayOfклиенты : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.School.DetailArrayOfклиенты members)

        // *** End programmer edit section *** (IIS.School.DetailArrayOfклиенты members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type клиенты by index.
        /// </summary>
        /// <summary>
        /// Adds object with type клиенты.
        /// </summary>
        public DetailArrayOfклиенты(IIS.School.Запись fЗапись) : 
                base(typeof(клиенты), ((ICSSoft.STORMNET.DataObject)(fЗапись)))
        {
        }
        
        public IIS.School.клиенты this[int index]
        {
            get
            {
                return ((IIS.School.клиенты)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.School.клиенты dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
