//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.School
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ПОЛ.
    /// </summary>
    // *** Start programmer edit section *** (ПОЛ CustomAttributes)

    // *** End programmer edit section *** (ПОЛ CustomAttributes)
    public enum ПОЛ
    {
        
        // *** Start programmer edit section *** (ПОЛ.Првра CustomAttributes)

        // *** End programmer edit section *** (ПОЛ.Првра CustomAttributes)
        [Caption("Мужской")]
        Првра,
        
        // *** Start programmer edit section *** (ПОЛ.папв CustomAttributes)

        // *** End programmer edit section *** (ПОЛ.папв CustomAttributes)
        [Caption("Женский")]
        папв,
        
        // *** Start programmer edit section *** (ПОЛ.папвв CustomAttributes)

        // *** End programmer edit section *** (ПОЛ.папвв CustomAttributes)
        [Caption("Средний")]
        папвв,
    }
}
