//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.School
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Услуги.
    /// </summary>
    // *** Start programmer edit section *** (Услуги CustomAttributes)

    // *** End programmer edit section *** (Услуги CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УслугиE", new string[] {
            "стоимость as \'Стоимость\'",
            "время as \'Время\'",
            "услуга as \'Услуга\'"})]
    [View("УслугиL", new string[] {
            "стоимость as \'Стоимость\'",
            "время as \'Время\'",
            "услуга as \'Услуга\'"})]
    public class Услуги : ICSSoft.STORMNET.DataObject
    {
        
        private int fстоимость;
        
        private int fвремя;
        
        private IIS.School.Услуга fуслуга;
        
        // *** Start programmer edit section *** (Услуги CustomMembers)

        // *** End programmer edit section *** (Услуги CustomMembers)

        
        /// <summary>
        /// время.
        /// </summary>
        // *** Start programmer edit section *** (Услуги.время CustomAttributes)

        // *** End programmer edit section *** (Услуги.время CustomAttributes)
        public virtual int время
        {
            get
            {
                // *** Start programmer edit section *** (Услуги.время Get start)

                // *** End programmer edit section *** (Услуги.время Get start)
                int result = this.fвремя;
                // *** Start programmer edit section *** (Услуги.время Get end)

                // *** End programmer edit section *** (Услуги.время Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Услуги.время Set start)

                // *** End programmer edit section *** (Услуги.время Set start)
                this.fвремя = value;
                // *** Start programmer edit section *** (Услуги.время Set end)

                // *** End programmer edit section *** (Услуги.время Set end)
            }
        }
        
        /// <summary>
        /// стоимость.
        /// </summary>
        // *** Start programmer edit section *** (Услуги.стоимость CustomAttributes)

        // *** End programmer edit section *** (Услуги.стоимость CustomAttributes)
        public virtual int стоимость
        {
            get
            {
                // *** Start programmer edit section *** (Услуги.стоимость Get start)

                // *** End programmer edit section *** (Услуги.стоимость Get start)
                int result = this.fстоимость;
                // *** Start programmer edit section *** (Услуги.стоимость Get end)

                // *** End programmer edit section *** (Услуги.стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Услуги.стоимость Set start)

                // *** End programmer edit section *** (Услуги.стоимость Set start)
                this.fстоимость = value;
                // *** Start programmer edit section *** (Услуги.стоимость Set end)

                // *** End programmer edit section *** (Услуги.стоимость Set end)
            }
        }
        
        /// <summary>
        /// услуга.
        /// </summary>
        // *** Start programmer edit section *** (Услуги.услуга CustomAttributes)

        // *** End programmer edit section *** (Услуги.услуга CustomAttributes)
        public virtual IIS.School.Услуга услуга
        {
            get
            {
                // *** Start programmer edit section *** (Услуги.услуга Get start)

                // *** End programmer edit section *** (Услуги.услуга Get start)
                IIS.School.Услуга result = this.fуслуга;
                // *** Start programmer edit section *** (Услуги.услуга Get end)

                // *** End programmer edit section *** (Услуги.услуга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Услуги.услуга Set start)

                // *** End programmer edit section *** (Услуги.услуга Set start)
                this.fуслуга = value;
                // *** Start programmer edit section *** (Услуги.услуга Set end)

                // *** End programmer edit section *** (Услуги.услуга Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УслугиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УслугиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УслугиE", typeof(IIS.School.Услуги));
                }
            }
            
            /// <summary>
            /// "УслугиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УслугиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УслугиL", typeof(IIS.School.Услуги));
                }
            }
        }
    }
}
