//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.School
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Услуга.
    /// </summary>
    // *** Start programmer edit section *** (Услуга CustomAttributes)

    // *** End programmer edit section *** (Услуга CustomAttributes)
    public enum Услуга
    {
        
        // *** Start programmer edit section *** (Услуга.Хуем CustomAttributes)

        // *** End programmer edit section *** (Услуга.Хуем CustomAttributes)
        Хуем,
        
        // *** Start programmer edit section *** (Услуга.по CustomAttributes)

        // *** End programmer edit section *** (Услуга.по CustomAttributes)
        по,
        
        // *** Start programmer edit section *** (Услуга.лбу CustomAttributes)

        // *** End programmer edit section *** (Услуга.лбу CustomAttributes)
        лбу,
        
        // *** Start programmer edit section *** (Услуга.Макияж CustomAttributes)

        // *** End programmer edit section *** (Услуга.Макияж CustomAttributes)
        [Caption("Макияж")]
        Макияж,
    }
}
